services:
  pay-service:
    container_name: pay-service
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - pay-service:/app
    ports:
      - "7005:8000"
    environment:
      - db_uri=postgresql://postgres:postgres@postgres:5432/paydb
      - app_host=0.0.0.0
      - app_port=8000
    depends_on:
      - pay-postgres

  pay-postgres:
    image: postgres:15
    container_name: pay-postgres
    restart: always
    environment:
      POSTGRES_DB: paydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pay-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pay-service:
  pay-db:
