services:
  pay-service:
    container_name: pay-service
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - pay-service:/app
    ports:
      - "7005:8000"

volumes:
  pay-service:
